spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3387}/${MYSQL_DATABASE:iems_test}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:iems}
    password: ${MYSQL_PASSWORD:iems_test_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:mongo_test}:${MONGO_INITDB_ROOT_PASSWORD:mongo_test_pwd}@${MONGO_HOST:localhost}:${MONGO_PORT:27818}/${MONGO_DATABASE:admin}?authSource=admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6881}
      password: ${REDIS_PASSWORD:redis_test_pwd} # Add Redis password
      timeout: 2s # Use standard duration format
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  sql:
    init:
      mode: never

app:
  environment: test