spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:iems_test}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:iems}
    password: ${MYSQL_PASSWORD:iems_test_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:mongo_test}:${MONGO_INITDB_ROOT_PASSWORD:mongo_test_pwd}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:admin}?authSource=admin
  sql:
    init:
      mode: never

app:
  environment: test